[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
tic_tac_toe = "61ZTuybsFkoAEWBvS2S5r6CgQ2xoG93x65CYm3CqDteY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/duck/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
